import React from 'react'
import { Inter } from 'next/font/google'
import '../globals.css';
import NavbarComponent from '@/components/NavbarComponent';
const inter = Inter({ subsets: ['latin'] })
import '../tailwind.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-rgb-gradient dark:bg-gray-900'>
        <header>
          <title>Game-Shop</title>
        </header>
        <header>
          <NavbarComponent />
        </header>
        {children}
      </body>
    </html>
  )
}
